#!/usr/bin/env python3

from os import path, system, makedirs

import termios
import sys
import tty

def getch():
    fd = sys.stdin.fileno()
    old_settings = termios.tcgetattr(fd)
    try:
        tty.setraw(fd)
        ch = sys.stdin.read(1)
    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, old_settings)
    return ch

def yes_no_prompt(question):
    print(question + " (y/n): ", end='', flush=True)
    while True:
        ch = getch().lower()
        if ch == 'y' or ch == 'Y':
            print('y')
            return True
        else:
            print('n')
            return False

def check_accident(session_data: list[str]):
    if session_data[0] == "" or session_data[1] == "q":
        exit(0)

session_data = input("Create Session\n>  ").split(":")
check_accident(session_data)
dir = path.dirname(path.realpath(__file__)) if len(session_data) <= 1 else session_data[1]

if not path.exists(dir):
    if yes_no_prompt("do you wish to create it?"):
        makedirs(dir, exist_ok=True)

system(f"tmux new-session -d -s {session_data[0]} -c {dir}")
exit(0)
