#!/bin/zsh

has_sessions_to_switch() {
    available_sessions=$(tmux ls | wc -l)
    if [[ $available_sessions -lt 2 ]];
    then
        exit 0
    else
        tmux display-popup -E "~/.config/tmux/tmux_switch_session 0"
        exit 0
    fi
}

switch_session() {
    current_session=$(tmux ls | grep "(attached)" | awk -F ':' '{print $1}')
    selected_session=$(tmux ls | xargs -I {} echo {} | awk -F ':' '{print $1}' | tr ' ' '\n' | grep -v $current_session | fzf)
    tmux switch-client -t $selected_session
}

if [[ $# -lt 1 ]]
then
    has_sessions_to_switch
else
    switch_session
fi
