#!/bin/zsh

current_session=$(tmux ls | grep "(attached)" | awk -F ':' '{print $1}')
selected_session=$(tmux ls | xargs -I {} echo {} | awk -F ':' '{print $1}' | tr ' ' '\n' | grep -v $current_session | fzf)
tmux switch-client -t $selected_session
