#!/bin/zsh

session=$(find ~/.playground/study ~/.playground/projects -mindepth 1 -maxdepth  1 -type d | fzf)
session_name=$(basename $session)

if ! tmux has-session -t $session_name 2> /dev/null; 
then tmux new-session -s $session_name -c $session -d
fi

if [ "$TERM_PROGRAM" = tmux ];
then tmux switch-client -t $session_name
else tmux attach -t $session_name
fi
